services:
  mongodb:
    image: mongo:latest
    container_name: nosql
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    mem_limit: 100MB
